name: CD - Deploy Task Management App

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Authenticate to GCP
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: projects/985227244631/locations/global/workloadIdentityPools/github-action-pool/providers/github
          service_account: github-actions-deploy@voltarocks-42-sandbox.iam.gserviceaccount.com

      - name: Setup gcloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Configure Docker
        run: gcloud auth configure-docker asia-southeast1-docker.pkg.dev --quiet

      # Install Encore CLI
      - name: Install Encore
        run: |
          curl -L https://encore.dev/install.sh | bash
          echo "$HOME/.encore/bin" >> $GITHUB_PATH

      # Build image using Encore
      - name: Build & Push Image with Encore
        run: |
          IMAGE=asia-southeast1-docker.pkg.dev/voltarocks-42-sandbox/cloud-engineer-repo/task-management:${{ github.sha }}

          rm -rf infra
          cd app

          cat <<EOF > encore.config.json
          {
            "secrets": {
              "AUTH_SECRET": "dummy_secret_for_build"
            }
          }
          EOF

          encore build docker $IMAGE --push --config encore.config.json

      # Get VM instance ID
      - name: Get MIG instance
        run: |
          MIG_NAME=$(gcloud compute instance-groups managed list --project=voltarocks-42-sandbox --zones=asia-southeast1-a --filter="baseInstanceName=task-mgmt" --format="value(name)")
          INSTANCE=$(gcloud compute instance-groups managed list-instances $MIG_NAME --project=voltarocks-42-sandbox --zone=asia-southeast1-a --format="value(instance.basename())" | head -n 1)
          
          if [ -z "$INSTANCE" ]; then
            echo "Error: No instance found in MIG $MIG_NAME"
            exit 1
          fi
          
          echo "INSTANCE_NAME=$INSTANCE" >> $GITHUB_ENV

      # SSH and Deploy with Docker Secret
      - name: Deploy Service with Docker Secrets
        run: |
          export GCLOUD_SSH_OPTS="--ssh-flag=-oStrictHostKeyChecking=no --ssh-flag=-oUserKnownHostsFile=/dev/null"

          gcloud compute ssh ${{ env.INSTANCE_NAME }} \
            --zone=asia-southeast1-a \
            --project=voltarocks-42-sandbox \
            --tunnel-through-iap \
            $GCLOUD_SSH_OPTS \
            --quiet \
            --command="
              set -e

              sudo gcloud auth configure-docker asia-southeast1-docker.pkg.dev --quiet
              IMAGE=asia-southeast1-docker.pkg.dev/voltarocks-42-sandbox/cloud-engineer-repo/task-management:${{ github.sha }}

              SHORT_SHA=\$(echo '${{ github.sha }}' | cut -c1-7)
              SECRET_NAME=\"task-env-\$SHORT_SHA\"
              RULE='(Host(\`duongquockiet.id.vn\`) && PathPrefix(\`/v1/\`)) || Path(\`/health\`)'
             
              echo 'Pulling image...'
              sudo docker pull \$IMAGE

              echo 'Creating env file...'
              echo \"DATABASE_URL=postgres://admin:${{ secrets.DB_PASSWORD }}@core_stack_postgres:5432/appdb\" > prod.env
              echo \"AUTH_SECRET=${{ secrets.AUTH_SECRET }}\" >> prod.env

              echo 'Creating docker secret...'
              cat prod.env | sudo docker secret create \$SECRET_NAME - || true
              rm prod.env

              if sudo docker service inspect task-management > /dev/null 2>&1; then
                echo 'Updating existing service...'

    
                OLD_SECRETS=\$(sudo docker service inspect task-management \
                  --format '{{range .Spec.TaskTemplate.ContainerSpec.Secrets}}--secret-rm {{.SecretName}} {{end}}' \
                  2>/dev/null || true)

                sudo docker service update \
                  --image \$IMAGE \
                  --with-registry-auth \
                  --secret-add source=\$SECRET_NAME,target=/.env \
                  \$OLD_SECRETS \
                  --force \
                  task-management

              else
                echo 'Creating new service...'

                sudo docker service create \
                  --name task-management \
                  --replicas 1 \
                  --network app_network \
                  --with-registry-auth \
                  --label traefik.enable=true \
                  --label traefik.http.routers.app.rule=\"\$RULE\" \
                  --label traefik.http.services.app.loadbalancer.server.port=8080 \
                  --secret source=\$SECRET_NAME,target=/.env \
                  \$IMAGE
              fi
            "